# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/date.proto

require 'google/protobuf'


descriptor_data = "\n\x10proto/date.proto\x12\x04\x64\x61te\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x42\x06Z\x04./pbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Date
  Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("date.Date").msgclass
end
