# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/employee.proto

require 'google/protobuf'

require 'proto/date_pb'


descriptor_data = "\n\x14proto/employee.proto\x12\x08\x65mployee\x1a\x10proto/date.proto\"\xcb\x02\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12(\n\noccupation\x18\x04 \x01(\x0e\x32\x14.employee.Occupation\x12\x14\n\x0cphone_number\x18\x05 \x03(\t\x12\x30\n\x07Project\x18\x06 \x03(\x0b\x32\x1f.employee.Employee.ProjectEntry\x12\x0e\n\x04text\x18\x07 \x01(\tH\x00\x12 \n\x05video\x18\x08 \x01(\x0b\x32\x0f.employee.VideoH\x00\x12\x1c\n\x08\x62irthday\x18\t \x01(\x0b\x32\n.date.Date\x1aI\n\x0cProjectEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.employee.Company.Project:\x02\x38\x01\x42\t\n\x07profile\"\x14\n\x07\x43ompany\x1a\t\n\x07Project\"\t\n\x07Project\"\x07\n\x05Video*M\n\nOccupation\x12\x16\n\x12OCCUPATION_UNKNOWN\x10\x00\x12\x0c\n\x08\x45NGINEER\x10\x01\x12\x0c\n\x08\x44\x45SIGNER\x10\x02\x12\x0b\n\x07MANAGER\x10\x03\x42\x06Z\x04./pbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Employee
  Employee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Employee").msgclass
  Company = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Company").msgclass
  Company::Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Company.Project").msgclass
  Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Project").msgclass
  Video = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Video").msgclass
  Occupation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Occupation").enummodule
end
