// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/employee.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 列挙型
type Occupation int32

const (
	// 必ずタグ番号0から始める必要がある
	// 0は慣習としてUNKNOWNを割り当てる
	Occupation_OCCUPATION_UNKNOWN Occupation = 0
	Occupation_ENGINEER           Occupation = 1
	Occupation_DESIGNER           Occupation = 2
	Occupation_MANAGER            Occupation = 3
)

// Enum value maps for Occupation.
var (
	Occupation_name = map[int32]string{
		0: "OCCUPATION_UNKNOWN",
		1: "ENGINEER",
		2: "DESIGNER",
		3: "MANAGER",
	}
	Occupation_value = map[string]int32{
		"OCCUPATION_UNKNOWN": 0,
		"ENGINEER":           1,
		"DESIGNER":           2,
		"MANAGER":            3,
	}
)

func (x Occupation) Enum() *Occupation {
	p := new(Occupation)
	*p = x
	return p
}

func (x Occupation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Occupation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_employee_proto_enumTypes[0].Descriptor()
}

func (Occupation) Type() protoreflect.EnumType {
	return &file_proto_employee_proto_enumTypes[0]
}

func (x Occupation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Occupation.Descriptor instead.
func (Occupation) EnumDescriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{0}
}

// スカラ型
type Employee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1とか2はタグ番号
	Id          int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Occupation  Occupation `protobuf:"varint,4,opt,name=occupation,proto3,enum=employee.Occupation" json:"occupation,omitempty"`
	PhoneNumber []string   `protobuf:"bytes,5,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// <key型, value型>
	Project map[string]*Company_Project `protobuf:"bytes,6,rep,name=Project,proto3" json:"Project,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Profile:
	//
	//	*Employee_Text
	//	*Employee_Video
	Profile       isEmployee_Profile `protobuf_oneof:"profile"`
	Birthday      *Date              `protobuf:"bytes,9,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_proto_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetOccupation() Occupation {
	if x != nil {
		return x.Occupation
	}
	return Occupation_OCCUPATION_UNKNOWN
}

func (x *Employee) GetPhoneNumber() []string {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *Employee) GetProject() map[string]*Company_Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *Employee) GetProfile() isEmployee_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Employee) GetText() string {
	if x != nil {
		if x, ok := x.Profile.(*Employee_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Employee) GetVideo() *Video {
	if x != nil {
		if x, ok := x.Profile.(*Employee_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *Employee) GetBirthday() *Date {
	if x != nil {
		return x.Birthday
	}
	return nil
}

type isEmployee_Profile interface {
	isEmployee_Profile()
}

type Employee_Text struct {
	Text string `protobuf:"bytes,7,opt,name=text,proto3,oneof"`
}

type Employee_Video struct {
	Video *Video `protobuf:"bytes,8,opt,name=video,proto3,oneof"`
}

func (*Employee_Text) isEmployee_Profile() {}

func (*Employee_Video) isEmployee_Profile() {}

// メッセージのネスト
type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_proto_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{1}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{2}
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{3}
}

type Company_Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company_Project) Reset() {
	*x = Company_Project{}
	mi := &file_proto_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company_Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company_Project) ProtoMessage() {}

func (x *Company_Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company_Project.ProtoReflect.Descriptor instead.
func (*Company_Project) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{1, 0}
}

var File_proto_employee_proto protoreflect.FileDescriptor

const file_proto_employee_proto_rawDesc = "" +
	"\n" +
	"\x14proto/employee.proto\x12\bemployee\x1a\x10proto/date.proto\"\xa1\x03\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x124\n" +
	"\n" +
	"occupation\x18\x04 \x01(\x0e2\x14.employee.OccupationR\n" +
	"occupation\x12!\n" +
	"\fphone_number\x18\x05 \x03(\tR\vphoneNumber\x129\n" +
	"\aProject\x18\x06 \x03(\v2\x1f.employee.Employee.ProjectEntryR\aProject\x12\x14\n" +
	"\x04text\x18\a \x01(\tH\x00R\x04text\x12'\n" +
	"\x05video\x18\b \x01(\v2\x0f.employee.VideoH\x00R\x05video\x12&\n" +
	"\bbirthday\x18\t \x01(\v2\n" +
	".date.DateR\bbirthday\x1aU\n" +
	"\fProjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.employee.Company.ProjectR\x05value:\x028\x01B\t\n" +
	"\aprofile\"\x14\n" +
	"\aCompany\x1a\t\n" +
	"\aProject\"\t\n" +
	"\aProject\"\a\n" +
	"\x05Video*M\n" +
	"\n" +
	"Occupation\x12\x16\n" +
	"\x12OCCUPATION_UNKNOWN\x10\x00\x12\f\n" +
	"\bENGINEER\x10\x01\x12\f\n" +
	"\bDESIGNER\x10\x02\x12\v\n" +
	"\aMANAGER\x10\x03B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_employee_proto_rawDescOnce sync.Once
	file_proto_employee_proto_rawDescData []byte
)

func file_proto_employee_proto_rawDescGZIP() []byte {
	file_proto_employee_proto_rawDescOnce.Do(func() {
		file_proto_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_employee_proto_rawDesc), len(file_proto_employee_proto_rawDesc)))
	})
	return file_proto_employee_proto_rawDescData
}

var file_proto_employee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_employee_proto_goTypes = []any{
	(Occupation)(0),         // 0: employee.Occupation
	(*Employee)(nil),        // 1: employee.Employee
	(*Company)(nil),         // 2: employee.Company
	(*Project)(nil),         // 3: employee.Project
	(*Video)(nil),           // 4: employee.Video
	nil,                     // 5: employee.Employee.ProjectEntry
	(*Company_Project)(nil), // 6: employee.Company.Project
	(*Date)(nil),            // 7: date.Date
}
var file_proto_employee_proto_depIdxs = []int32{
	0, // 0: employee.Employee.occupation:type_name -> employee.Occupation
	5, // 1: employee.Employee.Project:type_name -> employee.Employee.ProjectEntry
	4, // 2: employee.Employee.video:type_name -> employee.Video
	7, // 3: employee.Employee.birthday:type_name -> date.Date
	6, // 4: employee.Employee.ProjectEntry.value:type_name -> employee.Company.Project
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_employee_proto_init() }
func file_proto_employee_proto_init() {
	if File_proto_employee_proto != nil {
		return
	}
	file_proto_date_proto_init()
	file_proto_employee_proto_msgTypes[0].OneofWrappers = []any{
		(*Employee_Text)(nil),
		(*Employee_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_employee_proto_rawDesc), len(file_proto_employee_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_employee_proto_goTypes,
		DependencyIndexes: file_proto_employee_proto_depIdxs,
		EnumInfos:         file_proto_employee_proto_enumTypes,
		MessageInfos:      file_proto_employee_proto_msgTypes,
	}.Build()
	File_proto_employee_proto = out.File
	file_proto_employee_proto_goTypes = nil
	file_proto_employee_proto_depIdxs = nil
}
